version: '3.3'
services:
  apache:
    image: "httpd"
    links:
      - solr
      - nutch
    ports:
      - "80:80"
    volumes:
      - ./apache:/usr/local/apache2/htdocs
  solr:
    image: "solr:7.3.1"
    ports:
     - "8983:8983"
    # volumes:
      # - data:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - mycore
    volumes:
      - ./solr/web.xml:/opt/solr/server/solr-webapp/webapp/WEB-INF/web.xml
  nutch:
    image: "apache/nutch:release-1.15"
    links:
      - solr
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
    working_dir: /root/nutch
    command: '/root/nutch/bin/crawl -i -D solr.server.url=http://solr:8983/solr/mycore -s urls crawl 10'
    volumes:
        - ./nutch/index-writers.xml:/root/nutch/conf/index-writers.xml
        - ./nutch/nutch-site.xml:/root/nutch/conf/nutch-site.xml
        - ./nutch/regex-urlfilter.txt:/root/nutch/conf/regex-urlfilter.txt
        - ./nutch/seed.txt:/root/nutch/urls/seed.txt
